### ISSUE TITLE
Reverting (probs not)

### ISSUE THREAD

**Issue by ghost** [Umbra999/Analytics-Preventer#3]
Is there anyway to actually revert it back? As I'd like all my spec names to show up.
![image](https://user-images.githubusercontent.com/103474655/225748561-fe92c036-3150-4380-9774-d13c9b54b71e.png)

**Comment by Umbra999** [comment]
this just blocks specific analytics url and is not doing anything to your pc specs, the issue you have wont come from this tool lmao

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/103474655/233995640-93750f20-9333-4b74-9ab3-cd2722b664b6.png)
It seems it came from one of your other tools lmao.
